#!/usr/bin/env python3
"""
PulseK12 Newsletter Automation Engine
Main orchestrator that runs the full pipeline.

Pipeline:
1. Fetch articles from Google News RSS feeds
2. Deduplicate and filter articles
3. Classify into categories and select balanced menu
4. Scrape full article content with Firecrawl
5. Summarize with Claude 3.5 Sonnet
6. Email the formatted menu
"""

import sys
import os
import json
from datetime import datetime
from pathlib import Path

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Path to save summaries for finalize.py
DATA_DIR = Path(__file__).parent.parent / "data"
SUMMARIES_FILE = DATA_DIR / "latest_summaries.json"

from dotenv import load_dotenv

load_dotenv()

from src.feeds import fetch_all_feeds, filter_by_date
from src.deduper import deduplicate_articles, dedupe_stats, count_feed_appearances
from src.categorizer import (
    classify_all_articles,
    select_balanced_menu,
    print_distribution,
    filter_relevant_articles,
    is_blocked_source
)
from src.scraper import scrape_articles, scrape_article
from src.summarizer import (
    summarize_all_articles,
    summarize_article,
    format_summary_markdown,
    is_complete_summary,
    count_complete_summaries
)
from src.emailer import send_newsletter, preview_email, get_week_subject
from src.feeds import resolve_google_news_url


def save_summaries(summaries: list[dict]) -> None:
    """Save summaries to JSON file for finalize.py to use."""
    DATA_DIR.mkdir(exist_ok=True)

    data = {
        "generated_at": datetime.now().isoformat(),
        "count": len(summaries),
        "summaries": summaries
    }

    with open(SUMMARIES_FILE, "w") as f:
        json.dump(data, f, indent=2, default=str)

    print(f"  Saved summaries to {SUMMARIES_FILE}")


def format_menu(summaries: list[dict]) -> str:
    """Format all summaries into the newsletter menu for review."""
    today = datetime.now()
    date_str = today.strftime("%B %d, %Y")

    header = f"""# PulseK12 Weekly Menu
**Week of {date_str}**

Here are this week's top K-12 education stories for your review. Reply with the numbers you want to include.

---

"""

    body = ""
    for i, summary in enumerate(summaries, 1):
        if summary.get("success", False) and summary.get("summary"):
            emoji = summary.get("category_emoji", "📰")
            headline = summary.get("headline", "Untitled")
            url = summary.get("source_url", "#")
            source = summary.get("source_name", "")
            summary_text = summary.get("summary", "")
            body += f"**{i}.** {emoji} **[{headline}]({url})**\n{summary_text}\n*Source: {source}*\n\n"
        else:
            # Include failed summaries with basic info
            emoji = summary.get("category_emoji", "📰")
            headline = summary.get("headline", "Article")
            url = summary.get("source_url", "#")
            body += f"**{i}.** {emoji} **[{headline}]({url})**\n*(Summary unavailable)*\n\n"

    footer = """---

*Reply with the numbers you want (e.g., "1, 3, 5, 7, 9, 11") and I'll send you the final formatted issue.*

*Generated by PulseK12 Newsletter Engine*
"""

    return header + body + footer


def run_pipeline(
    days_back: int = 7,
    target_articles: int = 20,
    send_email: bool = True,
    preview_only: bool = False
) -> dict:
    """
    Run the full newsletter generation pipeline.

    Args:
        days_back: Number of days to look back for articles
        target_articles: Target number of articles for the menu
        send_email: Whether to send the email
        preview_only: If True, only preview without sending

    Returns:
        Dict with pipeline results and stats
    """
    stats = {
        "started_at": datetime.now().isoformat(),
        "days_back": days_back,
        "target_articles": target_articles
    }

    print("=" * 60)
    print("PulseK12 Newsletter Pipeline")
    print(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print("=" * 60)

    # Step 1: Fetch RSS feeds
    print("\n[1/8] Fetching RSS feeds...")
    articles = fetch_all_feeds(days_back=days_back)
    stats["fetched"] = len(articles)

    # Step 2: Filter by date
    print("\n[2/7] Filtering by date...")
    articles = filter_by_date(articles, days_back=days_back)
    stats["after_date_filter"] = len(articles)
    print(f"  {len(articles)} articles within date range")

    # Step 3: Count feed appearances (trending detection) - before deduplication
    print("\n[3/7] Counting feed appearances (trending detection)...")
    articles = count_feed_appearances(articles)
    multi_feed = sum(1 for a in articles if a.get("feed_appearance_count", 1) > 1)
    print(f"  {multi_feed} articles appear in multiple feeds")

    # Step 4: Deduplicate
    print("\n[4/7] Deduplicating...")
    articles = deduplicate_articles(articles)
    stats["after_dedupe"] = len(articles)
    print(f"  {len(articles)} unique articles")

    if len(articles) == 0:
        print("\nNo articles found! Aborting pipeline.")
        return {"success": False, "error": "No articles found", "stats": stats}

    # Step 5: Filter for relevance
    print("\n[5/8] Filtering for education relevance...")
    articles = filter_relevant_articles(articles)
    stats["after_relevance"] = len(articles)
    print(f"  {len(articles)} relevant education articles")

    # Step 6: Classify and balance (keep extra for backups)
    print("\n[6/8] Classifying and balancing...")
    articles = classify_all_articles(articles)
    # Select primary articles with balancing (max 3 local stories)
    primary_articles = select_balanced_menu(articles, target_count=target_articles, max_local=3)
    # Get additional backups from remaining articles (sorted by total_score)
    primary_set = set(id(a) for a in primary_articles)
    backup_articles = [a for a in articles if id(a) not in primary_set]
    backup_articles.sort(key=lambda x: x.get("total_score", 0), reverse=True)
    backup_articles = backup_articles[:target_articles]  # Keep up to 20 backups
    stats["selected"] = len(primary_articles)
    stats["backups"] = len(backup_articles)
    print(f"  Selected {len(primary_articles)} primary + {len(backup_articles)} backup articles")
    print_distribution(primary_articles)

    # Step 7: Scrape with Firecrawl
    print("\n[7/8] Scraping full content...")
    primary_articles = scrape_articles(primary_articles, max_articles=target_articles)
    scraped_count = sum(1 for a in primary_articles if a.get("full_content"))
    stats["scraped"] = scraped_count

    # Post-scrape filter: remove articles from bad domains/sources
    from src.categorizer import BLOCKED_DOMAINS, get_domain
    before_filter = len(primary_articles)
    filtered_primary = []
    removed_articles = []
    for article in primary_articles:
        # Check source name (works even without URL resolution)
        source = article.get("source", "")
        if is_blocked_source(source):
            removed_articles.append(article)
            continue

        # Check resolved URL domain
        resolved = article.get("resolved_url", article.get("url", ""))
        domain = get_domain(resolved)
        is_blocked = any(blocked in domain for blocked in BLOCKED_DOMAINS)
        if is_blocked:
            removed_articles.append(article)
        else:
            filtered_primary.append(article)

    if removed_articles:
        print(f"  Post-scrape filter: removed {len(removed_articles)} articles from blocked domains")
        # Add replacements from backups
        for removed in removed_articles:
            if backup_articles:
                replacement = backup_articles.pop(0)
                # Scrape the replacement
                url = replacement.get("url", "")
                resolved = resolve_google_news_url(url)
                replacement["resolved_url"] = resolved
                print(f"    Replacing with: {replacement.get('title', '')[:40]}...")

                from src.scraper import scrape_article as scrape_one, get_firecrawl_client
                import time
                time.sleep(7)  # Rate limit
                client = get_firecrawl_client()
                scrape_result = scrape_one(resolved, client)
                if scrape_result["success"]:
                    replacement["full_content"] = scrape_result["content"]
                    # Check if replacement is also from blocked domain
                    rep_domain = get_domain(resolved)
                    if not any(blocked in rep_domain for blocked in BLOCKED_DOMAINS):
                        filtered_primary.append(replacement)
                        print(f"      ✓ Added replacement")
                    else:
                        print(f"      ✗ Replacement also blocked")

    primary_articles = filtered_primary

    # Step 8: Summarize with Claude
    print("\n[8/8] Generating summaries with Claude...")
    summaries = summarize_all_articles(primary_articles)

    # Check for incomplete summaries and backfill
    complete, incomplete = count_complete_summaries(summaries)
    print(f"  Complete summaries: {complete}/{len(summaries)}")

    if incomplete > 0 and backup_articles:
        print(f"\n  Backfilling {incomplete} incomplete summaries...")
        # Find indices of incomplete summaries
        incomplete_indices = [i for i, s in enumerate(summaries) if not is_complete_summary(s)]

        # Process backups until we've replaced all incomplete or run out
        backups_used = 0
        for idx in incomplete_indices:
            if backups_used >= len(backup_articles):
                break

            backup = backup_articles[backups_used]
            backups_used += 1

            # Resolve URL and scrape backup
            url = backup.get("url", "")
            resolved = resolve_google_news_url(url)
            backup["resolved_url"] = resolved

            print(f"    Trying backup: {backup.get('title', '')[:40]}...")
            from src.scraper import scrape_article as scrape_one, get_firecrawl_client
            client = get_firecrawl_client()
            scrape_result = scrape_one(resolved, client)

            if scrape_result["success"]:
                backup["full_content"] = scrape_result["content"]
                new_summary = summarize_article(backup)

                if is_complete_summary(new_summary):
                    summaries[idx] = new_summary
                    print(f"      ✓ Replaced with good summary")
                else:
                    print(f"      ✗ Backup also incomplete, keeping original")
            else:
                print(f"      ✗ Scrape failed: {scrape_result['error'][:30]}")

        # Recount
        complete, incomplete = count_complete_summaries(summaries)
        print(f"  After backfill: {complete}/{len(summaries)} complete")

    stats["summarized"] = complete

    # Save summaries for finalize.py
    print("\nSaving summaries for finalization...")
    save_summaries(summaries)

    # Format the menu
    print("\nFormatting menu...")
    menu_content = format_menu(summaries)
    stats["menu_length"] = len(menu_content)

    # Preview or send
    if preview_only:
        preview_email(menu_content)
        stats["email_sent"] = False
    elif send_email:
        print("\nSending email...")
        result = send_newsletter(menu_content)
        stats["email_sent"] = result["success"]
        if not result["success"]:
            print(f"  Email error: {result['error']}")
    else:
        print("\nEmail sending disabled. Menu content:")
        print("-" * 40)
        print(menu_content)
        stats["email_sent"] = False

    # Final stats
    stats["completed_at"] = datetime.now().isoformat()

    print("\n" + "=" * 60)
    print("Pipeline Complete!")
    print(f"  Articles fetched: {stats['fetched']}")
    print(f"  After deduplication: {stats['after_dedupe']}")
    print(f"  Selected for menu: {stats['selected']}")
    print(f"  Successfully scraped: {stats['scraped']}")
    print(f"  Successfully summarized: {stats['summarized']}")
    print(f"  Email sent: {stats['email_sent']}")
    print("=" * 60)

    return {"success": True, "stats": stats, "menu": menu_content}


def main():
    """CLI entry point."""
    import argparse

    parser = argparse.ArgumentParser(description="PulseK12 Newsletter Generator")
    parser.add_argument(
        "--days", type=int, default=7,
        help="Number of days to look back (default: 7)"
    )
    parser.add_argument(
        "--articles", type=int, default=20,
        help="Target number of articles (default: 20)"
    )
    parser.add_argument(
        "--preview", action="store_true",
        help="Preview only, don't send email"
    )
    parser.add_argument(
        "--no-email", action="store_true",
        help="Skip email sending entirely"
    )

    args = parser.parse_args()

    result = run_pipeline(
        days_back=args.days,
        target_articles=args.articles,
        send_email=not args.no_email,
        preview_only=args.preview
    )

    sys.exit(0 if result["success"] else 1)


if __name__ == "__main__":
    main()
